# Generated by Django 3.1 on 2021-01-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetbl',
            name='empid',
            field=models.CharField(max_length=10),
        ),
    ]
