# Generated by Django 3.1 on 2021-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_admintbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtbl',
            name='pickTime',
            field=models.TimeField(null=True),
        ),
    ]
